AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template: ECS Fargate Cluster with an ALB pulling from an ECR image.'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select the VPC where your infrastructure is deployed.
    Default: vpc-09897f63d26c45074

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Select at least two public subnets for the Load Balancer and Fargate tasks.
    Default: subnet-0b6031fa99b6060a3,subnet-01bc6845bb66e1448

  EcrImageUri:
    Type: String
    Description: The full URI of your ECR image (e.g., ://amazonaws.com).
    Default: 024558321779.dkr.ecr.us-east-1.amazonaws.com/ecr-ecs:latest

  ContainerPort:
    Type: Number
    Default: 8501
    Description: The port number the application inside the container listens on.
    
  KmsKeySecrets:
    Type: String
    Description: The KMS Key ARN (AWS Default, not CMK) for encrypting the Bedrock Agent ID secret in Secrets Manager.
    Default: arn:aws:kms:us-east-1:024558321779:key/c31787c3-0a06-4a7c-817b-c7a625d5023d

Resources:
  
  # Secret for Bedrock Agent ID
  BedrockAgentSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name:  '/ecs/ecr-ecs/bedrock-agent-tmp'
      KmsKeyId: !Ref KmsKeySecrets
      Description: 'Secret for Bedrock Agent ID used by the ECS Fargate container.'
      SecretString: '{"BEDROCK_AGENT_ID": "124", "BEDROCK_AGENT_ALIAS_ID": "TSTALIASID", "AWS_DEFAULT_REGION": "us-east-1"}'
  
  # IAM Execution Role for Fargate Agent to pull from ECR and log to CloudWatch
  EcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Sid: AllowCloudWatchLogs
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                Resource: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/ecs/${AWS::StackName}-fargate-app:*'               
              - Effect: Allow
                Sid: AllowSecretsManagerAccess
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub 'arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/ecs/ecr-ecs/bedrock-agent-*'               
  #IAM Task Role for ECS Tasks (Optional, if your container needs to access AWS services)
  EcsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ['sts:AssumeRole']
      Policies:
        - PolicyName: ecs-task-role-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Sid: AllowExecutionCommandAccess
                Action:
                  - ssmmessages:CreateControlChannel
                  - ssmmessages:CreateDataChannel
                  - ssmmessages:OpenControlChannel
                  - ssmmessages:OpenDataChannel
                Resource: "*"             
  
  #KMS Key for encrypting CloudWatch Logs (Optional)
  CloudWatchKmsKey:
    Type: AWS::KMS::Key
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Description: KMS Key for encrypting CloudWatch Logs 
      Enabled: true
      KeySpec: SYMMETRIC_DEFAULT 
      KeyUsage: ENCRYPT_DECRYPT
      KeyPolicy: 
        Version: 2012-10-17
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:root'
            Action: kms:*
            Resource: '*'
          - Sid: Allow access for Key Administrators
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:user/michael.cruz@amtrak.com'
            Action: 
              - kms:Create*
              - kms:Describe*
              - kms:Enable*
              - kms:List*
              - kms:Put*
              - kms:Update*
              - kms:Revoke*
              - kms:Disable*
              - kms:Get*
              - kms:Delete*
              - kms:TagResource
              - kms:UntagResource
              - kms:ScheduleKeyDeletion
              - kms:CancelKeyDeletion
              - kms:RotateKeyOnDemand
            Resource: '*'  
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              AWS: !GetAtt EcsTaskExecutionRole.Arn
            Action: 
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: '*'
          - Sid: Allow service use of the key
            Effect: Allow
            Principal:
              Service: logs.us-east-1.amazonaws.com
            Action: 
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: '*'
            Condition:
              StringEquals:
                kms:EncryptionContext:aws:logs:arn: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/ecs/${AWS::StackName}-fargate-app'

  KMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/CloudWatchEncryptTBDAlias
      TargetKeyId: !Ref CloudWatchKmsKey
 
  # Log Group for Container Application Logs
  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub '/ecs/${AWS::StackName}-fargate-app'
      RetentionInDays: 7
      KmsKeyId: !GetAtt CloudWatchKmsKey.Arn

  # Security Group for the Application Load Balancer
  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow public HTTP traffic to the Load Balancer
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 10.0.0.0/8

  # Security Group for Fargate Tasks (Allows traffic ONLY from the ALB)
  FargateTaskSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from the ALB to Fargate tasks
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          CidrIp: 10.0.0.0/8

  # Application Load Balancer
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${AWS::StackName}-alb'
      Scheme: internal
      Type: application
      Subnets: !Ref SubnetIds
      SecurityGroups:
        - !Ref AlbSecurityGroup
      LoadBalancerAttributes:
        - Key: routing.http.drop_invalid_header_fields.enabled
          Value: 'true'

  # Target Group targeting Fargate Tasks using 'ip' target type
  AlbTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${AWS::StackName}-tg'
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Port: !Ref ContainerPort
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId

  # ALB Listener routing HTTP traffic to the Target Group
  AlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref AlbTargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

  # ECS Cluster
  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub '${AWS::StackName}-cluster'

  # ECS Task Definition configured for AWS Fargate
  EcsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${AWS::StackName}-task'
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt EcsTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt EcsTaskRole.Arn
      ContainerDefinitions:
        - Name: !Sub '${AWS::StackName}-container'
          Image: !Ref EcrImageUri
          Secrets:
            - Name: BEDROCK_AGENT_ID
              ValueFrom: !Ref BedrockAgentSecret
            - Name: BEDROCK_AGENT_ALIAS_ID
              ValueFrom: !Ref BedrockAgentSecret
            - Name: AWS_DEFAULT_REGION
              ValueFrom: !Ref BedrockAgentSecret  
          Cpu: 256
          Memory: 512
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudWatchLogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ecs

  # ECS Fargate Service connecting Tasks to the ALB
  EcsService:
    Type: AWS::ECS::Service
    DependsOn: AlbListener
    Properties:
      ServiceName: !Sub '${AWS::StackName}-service'
      Cluster: !Ref EcsCluster
      LaunchType: FARGATE
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: 2
      TaskDefinition: !Ref EcsTaskDefinition
      EnableExecuteCommand: true
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref FargateTaskSecurityGroup
          Subnets: !Ref SubnetIds
      LoadBalancers:
        - ContainerName: !Sub '${AWS::StackName}-container'
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref AlbTargetGroup

Outputs:
  ServiceUrl:
    Description: URL of the Application Load Balancer
    Value: !Sub 'http://${ApplicationLoadBalancer.DNSName}'
